services:
  vibeindex:
    image: ghcr.io/its-the-vibe/vibeserver:latest
    pull_policy: always
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=8080
      - DIST_DIR=/app/static
    read_only: true
    restart: on-failure:10
    volumes:
      - ./static:/app/static:ro
      - ./static/config.json:/app/static/config.json:ro
